import React, { useEffect, useState } from 'react';
import './App.css';
import { getEmployees } from './utils/employees';
import Header from './components/employee-create/CreateHeader';
import Button from './components/employee-create/CreateButton';
import Form from './components/employee-create/CreateForm';
import Input from './components/employee-create/CreateInput';
import EmployeesTable from './components/EmployeesTable';
import initialFields from './data';
import { FaEye, FaEyeSlash, FaRedo} from 'react-icons/fa';
import SearchBar from './components/SearchComponent/SearchBar';


function App() {
  const [showForm, setShowForm] = useState(false);
  const [formFields, setFormFields] = useState(initialFields);
  const [employees, setEmployees] = useState([]);
  const formIsInvalid = formFields.some(
    ({ value, validate }) => !validate(value)
  );

  const [
    { value: fName },
    { value: lName },
    { value: email },
    { value: location },
    { value: phone },
  ] = formFields;

  useEffect(() => {
    const storedEmployees = getEmployees().then((data) => {
      console.log('Employees Data:', data.results);
      setEmployees(data.results);
    });
  }, []);

  const handleFormSubmit = (e) => {
    e.preventDefault();

    alert(
      `Hey ${fName} ${lName}! This is your info: Your email is ${email}, you're located at ${location},
       and your number is ${phone}!`
    );
    setEmployees([
      ...employees,
      {
        name: {
          first: fName,
          last: lName,
        },
        phone: phone,
        email: email,
        location: {
          city: location.split(', ')[0],
          state: location.split(', ')[1],
        },
      },
    ]);
    // setEmployees(e)
    setFormFields(initialFields);
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    const newFormFields = formFields.map((field) => {
      if (field.name === name) {
        return { ...field, value };
      }
      return field;
    });
    setFormFields(newFormFields);
  };

  const handleShowCard = () => {
    setShowForm(!showForm);
  };

  //>--- Filter Methods for EmployeesTable 
  const filterByFirstName = () => {
    // # To avoid mutating state directly (a React no-no) I created a brand new array to filter/sort and spread in the existing values...
    const updatedEmployees = [...employees];
    updatedEmployees.sort(function (a, b) {
      // # I had to alter the two lines below to point to the appropriate key/val pairs in the employee objects generated by the API.
      let nameA = a.name.first.toUpperCase(); // ignore upper and lowercase
      let nameB = b.name.first.toUpperCase(); // ignore upper and lowercase
      if (nameA < nameB) {
        return -1; //nameA comes first
      }
      if (nameA > nameB) {
        return 1; // nameB comes first
      }
      return 0; // names must be equal
    });

    // # Once the sort/filter is completed, I'm updating state with the new array.
    setEmployees(updatedEmployees);
    //  console.log(tableData)
  };

  const filterByLastName = () => {
    
    const updatedEmployees = [...employees];
    updatedEmployees.sort(function (a, b) {
      // # I had to alter the two lines below to point to the appropriate key/val pairs in the employee objects generated by the API.
      let nameA = a.name.last.toUpperCase(); // ignore upper and lowercase
      let nameB = b.name.last.toUpperCase(); // ignore upper and lowercase
      if (nameA < nameB) {
        return -1; //nameA comes first
      }
      if (nameA > nameB) {
        return 1; // nameB comes first
      }
      return 0; // names must be equal
    });

    // # Once the sort/filter is completed, I'm updating state with the new array.
    setEmployees(updatedEmployees);
   
  };

  // const filterByEmail = () => {
    
  //   const updatedEmployees = [...employees];
  //   updatedEmployees.sort(function (a, b) {
  //     let emailA = a.email.toUpperCase(); // ignore upper and lowercase
  //     let emailB = b.email.toUpperCase(); // ignore upper and lowercase
  //     if (emailA < emailB) {
  //       return -1; 
  //     }
  //     if (emailA > emailB) {
  //       return 1; 
  //     }
  //     return 0; 
  //   });

  //   // # Once the sort/filter is completed, I'm updating state with the new array.
  //   setEmployees(updatedEmployees);
   
  // };

  // const filterByLocation = () => {
    
  //   const updatedEmployees = [...employees];
  //   updatedEmployees.sort(function (a, b) {
  //     let cityA = a.location.city.toUpperCase(); // ignore upper and lowercase
  //     let cityB = b.location.city.toUpperCase(); // ignore upper and lowercase
  //     if (cityA < cityB) {
  //       return -1; 
  //     }
  //     if (cityA > cityB) {
  //       return 1; 
  //     }
  //     return 0; 
  //   });

  //   // # Once the sort/filter is completed, I'm updating state with the new array.
  //   setEmployees(updatedEmployees);
   
  // };

  const filterByPhone = () => {
    
    const updatedEmployees = [...employees];
    updatedEmployees.sort(function (a, b) {
      let phoneA = a.phone.toUpperCase(); // ignore upper and lowercase
      let phoneB = b.phone.toUpperCase(); // ignore upper and lowercase
      if (phoneA < phoneB) {
        return -1; 
      }
      if (phoneA > phoneB) {
        return 1; 
      }
      return 0; 
    });

    // # Once the sort/filter is completed, I'm updating state with the new array.
    setEmployees(updatedEmployees);
   
  };

  const filterName = (v, bool) => {
    
    const updatedEmployees = [...employees];
    updatedEmployees.sort(function (a, b) {
     
      if (!bool) {

      let nameA = a.name[v].toUpperCase(); // ignore upper and lowercase
      let nameB = b.name[v].toUpperCase(); // ignore upper and lowercase

      if (nameA < nameB) {
        return -1; //nameA comes first
      }
      if (nameA > nameB) {
        return 1; // nameB comes first
      }
      return 0; // names must be equal
    }

    else if (bool) {

      let nameA = a.name[v].toUpperCase(); // ignore upper and lowercase
      let nameB = b.name[v].toUpperCase(); // ignore upper and lowercase

      if (nameA > nameB) {
        return -1; //nameA comes first
      }
      if (nameA < nameB) {
        return 1; // nameB comes first
      }
      return 0; // names must be equal
    }

  });

    // # Once the sort/filter is completed, I'm updating state with the new array.
    setEmployees(updatedEmployees);
   
  };

  const filterByEmailOrPhone = (v, bool) => {
    
    const updatedEmployees = [...employees];
    updatedEmployees.sort(function (a, b) {
     
      if (!bool) {

      let nameA = a[v].toUpperCase(); // ignore upper and lowercase
      let nameB = b[v].toUpperCase(); // ignore upper and lowercase

      if (nameA < nameB) {
        return -1; //nameA comes first
      }
      if (nameA > nameB) {
        return 1; // nameB comes first
      }
      return 0; // names must be equal
    }

    else if (bool) {

      let nameA = a[v].toUpperCase(); // ignore upper and lowercase
      let nameB = b[v].toUpperCase(); // ignore upper and lowercase

      if (nameA > nameB) {
        return -1; //nameA comes first
      }
      if (nameA < nameB) {
        return 1; // nameB comes first
      }
      return 0; // names must be equal
    }

  });

    // # Once the sort/filter is completed, I'm updating state with the new array.
    setEmployees(updatedEmployees);
   
  };

  const filterByLocation = (v, bool) => {
    
    const updatedEmployees = [...employees];
    updatedEmployees.sort(function (a, b) {
     
      if (!bool) {

      let nameA = a.location[v].toUpperCase(); // ignore upper and lowercase
      let nameB = b.location[v].toUpperCase(); // ignore upper and lowercase

      if (nameA < nameB) {
        return -1; //nameA comes first
      }
      if (nameA > nameB) {
        return 1; // nameB comes first
      }
      return 0; // names must be equal
    }

    else if (bool) {

      let nameA = a.location[v].toUpperCase(); // ignore upper and lowercase
      let nameB = b.location[v].toUpperCase(); // ignore upper and lowercase

      if (nameA > nameB) {
        return -1; //nameA comes first
      }
      if (nameA < nameB) {
        return 1; // nameB comes first
      }
      return 0; // names must be equal
    }

  });

    // # Once the sort/filter is completed, I'm updating state with the new array.
    setEmployees(updatedEmployees);
   
  };

  const handleSearch = (e) =>{
    console.log(e.target.value);
  }

  return (
    <div className="newEmployeeBody">

        <div className='title'>
          <Header type='h4'>Bitwise/Alphaworks Employee Directory</Header>
        </div>
    
                  
    
      <div className="headerNewEmployee">
        <Header type="h8">Add a New Employee:</Header>
        {!showForm ? (
          <FaEye onClick={handleShowCard} />
        ) : (
          <FaEyeSlash onClick={handleShowCard} />
        )}
      </div>

      {!showForm ? (
        ''
      ) : (
        <div className=" card text-black bg-success formBody">
          <div className="card-body">
            <Form onSubmit={handleFormSubmit} className="formBody">
              {formFields.map(
                ({
                  label,
                  name,
                  type,
                  placeholder,
                  value,
                  errorMessage,
                  validate,
                }) => (
                  <Input
                    key={name}
                    label={label}
                    name={name}
                    type={type}
                    placeholder={placeholder}
                    value={value}
                    onChange={handleInputChange}
                    errorMessage={errorMessage}
                    isValid={validate(value)}
                  />
                )
              )}
              <Button
                type="submit"
                disabled={formIsInvalid}
                className={
                  !formIsInvalid
                    ? 'btn btn-info mt-3 addPerBtn'
                    : 'btn btn-secondary disabled mt-3 addPerBtn'
                }
              >
                Add New Employee
              </Button>
            </Form>
          </div>
        </div>
      )}
      
      <div className='headerSearchBar'>
        <Header type='h8'>View/Search Employees:</Header>
        <FaRedo onClick={handleShowCard}/>
      </div>
      <SearchBar onClick={handleSearch}/>

      <EmployeesTable
        employees={employees}
        filterName={filterName}
        filterByFirstName={filterByFirstName}
        filterByLastName={filterByLastName}
        filterByEmailOrPhone={filterByEmailOrPhone}
        filterByLocation={filterByLocation}
        filterByPhone={filterByPhone}
      />

    </div>
  );
}



export default App;
